[package]
name = "clinews"
version = "0.1.0"
edition = "2021"

description = "A simple cli news reader app"
license = "MIT"
authors = ["revandrazm"]

[dependencies]
crossterm = "0.23.2"
dotenv = "0.15.0"
newsapi = {path = "./newsapi"}
termimad = "0.20.2"
